services:
  concursos:
    build: .
    container_name: concursos
    hostname: concursos
    restart: always
    volumes: 
      - ./concursos:/servico
      - ./dados:/dados
    env_file:
      - .env
    environment:
      - PYTHONPATH=/
    ports: 
      - 8000:5000
    command: python3 /servico/servico.py
    networks: 
      - rede-concursos
  cargos:
    build: .
    container_name: cargos
    hostname: cargos
    restart: always
    volumes: 
      - ./cargos:/servico
      - ./dados:/dados
    env_file:
      - .env
    environment:
      - PYTHONPATH=/
    ports: 
      - 8001:5000
    command: python3 /servico/servico.py
    networks: 
      - rede-concursos
  cronogramas:
    build: .
    container_name: cronogramas
    hostname: cronogramas
    restart: always
    volumes: 
      - ./cronogramas:/servico
      - ./dados:/dados
    env_file:
      - .env
    environment:
      - PYTHONPATH=/
    ports: 
      - 8002:5000
    command: python3 /servico/servico.py
    networks: 
      - rede-concursos

  dados:
    image: postgres:latest
    container_name: dados
    hostname: dados
    restart: always
    ports:
      - "8003:5432"
    env_file:
      - .env
    volumes:
      - ./seligaconcurseiro.sql:/docker-entrypoint-initdb.d/seligaconcurseiro.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - rede-concursos

networks:
  rede-concursos:
    external: true
